"""Added tables

Revision ID: eb14f0473b4c
Revises: 726b8d7fe485
Create Date: 2024-01-11 12:51:36.451752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb14f0473b4c'
down_revision = '726b8d7fe485'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classes',
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('class_id')
    )
    op.create_table('students',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('student_id')
    )
    op.create_table('teachers',
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('teacher_id')
    )
    op.create_table('enrollments',
    sa.Column('enrollment_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('enrollment_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.class_id'], name=op.f('fk_enrollments_class_id_classes')),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], name=op.f('fk_enrollments_student_id_students')),
    sa.PrimaryKeyConstraint('enrollment_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('enrollments')
    op.drop_table('teachers')
    op.drop_table('students')
    op.drop_table('classes')
    # ### end Alembic commands ###
